version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: parkadmin
      POSTGRES_PASSWORD: 20park22ADMIN
      POSTGRES_DB: parking
    networks:
      - dev
networks:
  dev:
